name: Shared Deploy (Reusable)
on:
  workflow_call:

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: '18'
      - run: node -v
